openapi: 3.0.3
info:
  title: MetaWave Radio API
  version: 0.6.0
servers:
  - url: http://localhost:8000

components:
  securitySchemes:
    MetaWaveToken:
      type: apiKey
      in: header
      name: X-METAWAVE-TOKEN

paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: OK

  /generate-token:
    post:
      summary: Generiert einen temporären Token
      responses:
        "200":
          description: Token erzeugt
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  expiresIn:
                    type: integer

  /stream:
    get:
      summary: Liefert den Endlos-Radio-Stream
      description: Audio Stream (extern testen)
      security:
        - MetaWaveToken: []
      responses:
        "200":
          description: Stream gestartet

  /meta:
    get:
      summary: Liefert Song Meta
      security:
        - MetaWaveToken: []
      responses:
        "200":
          description: Meta-Daten des aktuellen Songs
          content:
            application/json:
              schema:
                type: object
                properties:
                  song:
                    type: string
                  index:
                    type: integer
                  total:
                    type: integer

  /skip:
    post:
      summary: Überspringt das aktuelle Lied
      security:
        - MetaWaveToken: []
      responses:
        "200":
          description: Song übersprungen
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean

  /ws:
    get:
      summary: WebSocket Endpoint
      description: ws://host:8000/ws?code=TOKEN
      security:
        - MetaWaveToken: []
      responses:
        "101":
          description: WebSocket Verbindung hergestellt