services:
  downloader:
    container_name: downloader
    build:
      context: ../..
      dockerfile: docker/metawave_server/dockerfile.downloader
    volumes:
      - songs:/songs
    env_file:
      - ../metawave_server/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: "no"
  radio:
    container_name: server
    build:
      context: ../..
      dockerfile: docker/metawave_server/dockerfile.radio
    env_file:
      - ../metawave_server/.env
    volumes:
      - songs:/songs
    ports:
      - "8000:8000"
    depends_on:
      downloader:
        condition: service_completed_successfully
      signal-api:
        condition: service_started
    restart: unless-stopped

volumes:
  songs:
  signal-data: