services:
  downloader:
    container_name: downloader
    build:
      context: ../..
      dockerfile: docker/metawave_server/dockerfile.downloader
    volumes:
      - songs:/songs
    env_file:
      - ../metawave_server/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
  radio:
    container_name: server
    build:
      context: ../..
      dockerfile: docker/metawave_server/dockerfile.radio
    env_file:
      - ../metawave_server/.env
    volumes:
      - songs:/songs
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  songs:
