FROM node:20-slim

RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app

COPY app/metawave_server/radio/package.json .
RUN npm install

COPY app/metawave_server/radio .

VOLUME ["/songs"]

EXPOSE 8000

CMD ["node", "server.js"]