FROM python:3.12-slim

RUN apt-get update && apt-get install -y ffmpeg
RUN apt-get install -y nodejs npm

WORKDIR /app

COPY app/metawave_server/downloader/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/metawave_server/downloader/update_playlist.py .

VOLUME ["/songs"]

ENV PYTHONUNBUFFERED=1
CMD ["python", "-u", "update_playlist.py"]