services:
  app:
    container_name: client
    build: 
      context: ../..
      dockerfile: docker/metawave_app/dockerfile.app
    env_file:
      - ../metawave_app/.env
    ports:
      - "80:8081"