SET
  SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

START TRANSACTION;

SET
  time_zone = "+00:00";

-- Create Database (if not exists)
CREATE DATABASE IF NOT EXISTS database_metawave;

USE database_metawave;

-- Create Tables (if not exists)
CREATE TABLE IF NOT EXISTS wave_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(255) NOT NULL,
  year INT NOT NULL,
  month INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_month (year, month)
);

CREATE TABLE IF NOT EXISTS email_notificationrecipient (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS radio_schedule (
  id TINYINT PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  start_time CHAR(5) NOT NULL DEFAULT '09:00',
  end_time CHAR(5) NOT NULL DEFAULT '17:00',
  CHECK (id = 1)
);

INSERT IGNORE INTO radio_schedule (id) VALUES (1);

CREATE TABLE IF NOT EXISTS playlists (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(1024) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

COMMIT;